# Generated by Django 2.2.19 on 2021-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], verbose_name='性別')),
                ('age', models.IntegerField(blank=True, choices=[(1, '10代'), (2, '20~60代'), (3, '70代以上')], verbose_name='年齢')),
            ],
        ),
        migrations.CreateModel(
            name='VgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vg_name', models.CharField(max_length=100, verbose_name='野菜の名前')),
                ('Vg_energie', models.CharField(max_length=100, verbose_name='エネルギー')),
                ('Vg_protein', models.CharField(max_length=100, verbose_name='プロテイン')),
                ('Vg_lipids', models.CharField(max_length=100, verbose_name='脂質')),
            ],
        ),
    ]
