# Generated by Django 2.2.19 on 2021-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgmodel',
            name='Vg_energie',
            field=models.CharField(max_length=100, null=True, verbose_name='エネルギー'),
        ),
        migrations.AlterField(
            model_name='vgmodel',
            name='Vg_lipids',
            field=models.CharField(max_length=100, null=True, verbose_name='脂質'),
        ),
        migrations.AlterField(
            model_name='vgmodel',
            name='Vg_name',
            field=models.CharField(max_length=100, null=True, verbose_name='野菜の名前'),
        ),
        migrations.AlterField(
            model_name='vgmodel',
            name='Vg_protein',
            field=models.CharField(max_length=100, null=True, verbose_name='プロテイン'),
        ),
    ]
