# Generated by Django 2.2.19 on 2021-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VGyapp', '0002_auto_20210307_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgmodel',
            name='Vg_name',
            field=models.CharField(max_length=100, verbose_name='野菜の名前'),
        ),
    ]
